#!/usr/bin/bash

# Convert a C file generated by pbres to a C++ file

# note that initialization of flexible array member is not supported
# by clang

input=$1
output=$2

sed -n \
    -e "{s/const ibitmap/extern const ibitmap/g; " \
    -e "s/unsigned char data\[\]/unsigned char data\[10000\]/g;" \
    -e "w ${output}" \
    -e "}" \
   "${input}"
# use of multiple expressions is required since everything that
# follows the w is part of the filename
