# Generate source with icons

set(ICONS
  ${CMAKE_SOURCE_DIR}/icons/icon_01n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_02n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_03n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_04n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_09n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_10n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_11n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_13n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_50n_2x.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_close.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_direction.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_display_settings.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_favorite.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_key.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_measuring_tape.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_menu.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_radio_button_checked.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_radio_button_unchecked.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_refresh.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_software_version.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_software_version_check.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_sunrise.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_sunset.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_taranis.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_wallpaper.bmp
  ${CMAKE_SOURCE_DIR}/icons/icon_warning.bmp
)
find_program(CONVERT_RESOURCES
  NAMES
  convert_resources.sh
  PATHS
  scripts
  REQUIRED
  DOC "Convert a C file generated by pbres to a C++ file"
)
add_custom_command(
  OUTPUT icon_resources.c
  COMMAND ${PBRES} -c ${CMAKE_CURRENT_BINARY_DIR}/icon_resources.c -8 ${ICONS}
  DEPENDS ${ICONS}
  COMMENT "Convert icons to C code"
)

add_custom_command(
  OUTPUT icon_resources.cc
  COMMAND ${CONVERT_RESOURCES} ${CMAKE_CURRENT_BINARY_DIR}/icon_resources.c ${CMAKE_CURRENT_BINARY_DIR}/icon_resources.cc
  DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/icon_resources.c
  COMMENT "Convert icons to C++ code"
)

list(APPEND ICONS_SOURCES
  ${CMAKE_CURRENT_BINARY_DIR}/icon_resources.cc
)
