name: Build with SDK-6.11

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Git ref of sources to build'
        required: true
        type: string

env:
  SDK_VERSION: "6.11"
  DEVICE_FAMILY: "RK3566"

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
          fetch-depth: 0
          submodules: true

      - name: Install build dependencies
        run: |
          sudo apt-get update -
          sudo apt-get install --no-install-recommends -y \
                7zip \
                build-essential \
                ca-certificates \
                clang-15 \
                cmake \
                git \
                pkg-config \
                wget \
                zip

      - name: Install PocketBook SDK
        run: |
          ./scripts/install_sdk.sh --family ${DEVICE_FAMILY} \
                                   --sdk-version ${SDK_VERSION} \
                                   --path .
          rm SDK-${DEVICE_FAMILY}-${SDK_VERSION}.7z

      - name: Build application
        run: |
          source build_env.sh
          python3 -m ensurepip
          python3 -m pip install jinja2

          cmake -S . -B build \
                -DCMAKE_TOOLCHAIN_FILE=${SDK_ROOT_PATH}/share/cmake/arm_conf.cmake
          wget --directory-prefix=build/gsl/src/ https://ftp.gnu.org/gnu/gsl/gsl-2.7.1.tar.gz
          cd build
          make taranis.app archive installer checksum

          mkdir artifact
          cp taranis.{app,pbi,sha256,zip} artifact
 
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          path: build/artifact
          if-no-files-found: error

