name: Create release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-24.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.collect_vcs_data.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
  
      - name: Collect VCS data
        id: collect_vcs_data
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Determine release type
        id: determine_release_type
        run: |
          if [[ "${{ env.TAG_NAME }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "PRERELEASE=false" >> $GITHUB_ENV
            echo "RELEASE_NAME=Release ${{ steps.collect_vcs_data.outputs.version }}" >> $GITHUB_ENV
          else
            echo "PRERELEASE=true" >> $GITHUB_ENV
            echo "RELEASE_NAME=Pre-release ${{ steps.collect_vcs_data.outputs.version }}" >> $GITHUB_ENV
          fi
  
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: true
          prerelease: ${{ env.PRERELEASE }}
          body: |
           See [News file](https://github.com/orontee/taranis/blob/${{ env.TAG_NAME }}/NEWS.md) for release content.

           ## How to install


           Copy the `taranis.pbi` file to the device, then open the corresponding "book" using the library application.

           An alternative is to manually copy the files from the `taranis.zip` archive to the `applications` directory of the device.

           💡 Make sure to install artifacts corresponding to the device firmware (6.8 or 6.10).


  build-with-sdk-6-10:
    needs: create-release
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        family: [B288, B300]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Install build dependencies
        run: |
          sudo apt-get update -
          sudo apt-get install --no-install-recommends -y \
                7zip \
                build-essential \
                ca-certificates \
                clang-15 \
                cmake \
                git \
                pkg-config \
                python3-jinja2 \
                wget \
                zip

      - name: Install PocketBook SDK
        run: |
          ./scripts/install_sdk.sh --family ${{ matrix.family}} \
                                   --sdk-version 6.10 \
                                   --path .
          rm SDK-${{ matrix.family }}-6.10.7z

      - name: Build application
        run: |
          source build_env.sh

          cmake -S . -B build \
                -DCMAKE_TOOLCHAIN_FILE=${SDK_ROOT_PATH}/share/cmake/arm_conf.cmake
          cmake --build build \
                --target taranis.app archive installer checksum

          mkdir build/artifact
          cp build/taranis.{app,pbi,sha256,zip} build/artifact

          pushd build/artifact
          zip artifact.zip taranis.{app,pbi,sha256,zip}

      - name: Upload pbi artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/artifact/taranis.pbi
          asset_name: taranis-${{ needs.create-release.outputs.version }}_firmware-6.10-${{ matrix.family }}.pbi
          asset_content_type: application/zip
  
      - name: Upload zip artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/artifact/taranis.zip
          asset_name: taranis-${{ needs.create-release.outputs.version }}_firmware-6.10-${{ matrix.family }}.zip
          asset_content_type: application/zip
  
      - name: Upload SHA256 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/artifact/taranis.sha256
          asset_name: taranis-${{ needs.create-release.outputs.version }}_firmware-6.10-${{ matrix.family }}.sha256
          asset_content_type: text/plain

      - name: Upload archive artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/artifact/artifact.zip
          asset_name: artifact-${{ needs.create-release.outputs.version }}_firmware-6.10-${{ matrix.family }}.zip
          asset_content_type: application/zip

  build-with-sdk-6-8:
    needs: create-release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        family: [B288, B300]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Install build dependencies
        run: |
          sudo apt-get update -
          sudo apt-get install --no-install-recommends -y \
                7zip \
                build-essential \
                ca-certificates \
                clang \
                cmake \
                git \
                libtinfo5 \
                pkg-config \
                python3-jinja2 \
                wget \
                zip
  
      - name: Install PocketBook SDK
        run: |
          ./scripts/install_sdk.sh --family ${{ matrix.family }} \
                                   --sdk-version 6.8 \
                                   --path .
          rm SDK-${{ matrix.family }}-6.8.7z
  
      - name: Build application
        run: |
          source build_env.sh
  
          cmake -S . -B build \
                -DCMAKE_TOOLCHAIN_FILE=${SDK_ROOT_PATH}/share/cmake/arm_conf.cmake
          cmake --build build \
                --target taranis.app archive installer checksum
  
          mkdir build/artifact
          cp build/taranis.{app,pbi,sha256,zip} build/artifact

          pushd build/artifact
          zip artifact.zip taranis.{app,pbi,sha256,zip}
  
      - name: Upload pbi artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/artifact/taranis.pbi
          asset_name: taranis-${{ needs.create-release.outputs.version }}_firmware-6.8-${{ matrix.family }}.pbi
          asset_content_type: application/zip
  
      - name: Upload zip artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/artifact/taranis.zip
          asset_name: taranis-${{ needs.create-release.outputs.version }}_firmware-6.8-${{ matrix.family }}.zip
          asset_content_type: application/zip
  
      - name: Upload SHA256 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/artifact/taranis.sha256
          asset_name: taranis-${{ needs.create-release.outputs.version }}_firmware-6.8-${{ matrix.family }}.sha256
          asset_content_type: text/plain

      - name: Upload archive artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/artifact/artifact.zip
          asset_name: artifact-${{ needs.create-release.outputs.version }}_firmware-6.8-${{ matrix.family }}.zip
          asset_content_type: application/zip
  
